[package]
name = "tfc"
description = "The Fat Controller. A library for simulating mouse and keyboard events. Features an iOS app for remote control."
keywords = ["keyboard", "mouse", "automation", "control"]
version = "0.1.0"
authors = ["Kerndog73 <kerndog73@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"], optional = true }
tokio-stream = { version = "0.1", optional = true }
warp = { version = "0.3", optional = true }
log = { version = "0", optional = true }
pretty_env_logger = { version = "0", optional = true }
futures = { version = "0.3", optional = true }

[build-dependencies]
heck = "0.3"

[features]
with-server = ["tokio", "tokio-stream", "warp", "log", "pretty_env_logger", "futures"]

[lib]
name = "tfc"
path = "src/lib.rs"

[[bin]]
name = "tfc-server"
path = "src/bin/server/main.rs"
required-features = ["with-server"]

[profile.release]
lto = true
