[package]
name = "keyboard"
version = "0.1.0"
authors = ["Kerndog73 <kerndog73@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
log = "0"
pretty_env_logger = "0"
futures = "0.3"
enigo = "0"
tokio-stream = "0.1"
askama = { version = "0.10", features = ["with-warp"] }
askama_warp = "0.11"
core-graphics = { version = "0.22", features = ["highsierra"] }
foreign-types = "0.3"

[profile.release]
lto = true

#[patch.crates-io]
#enigo = { path = "../enigo" }
