[package]
name = "tfc"
description = "The Fat Controller. A library for simulating mouse and keyboard events. Repo contains an iOS app for remote control."
keywords = ["keyboard", "mouse", "automation", "control"]
version = "0.1.0"
authors = ["Kerndog73 <kerndog73@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
heck = "0.3"

[profile.release]
lto = true
