[package]
name = "tfc"
description = "The Fat Controller. A library for simulating mouse and keyboard events."
keywords = ["keyboard", "mouse", "automation", "control"]
version = "0.3.0"
authors = ["Kerndog73 <kerndog73@gmail.com>"]
edition = "2018"
repository = "https://github.com/Kerndog73/The-Fat-Controller"
homepage = "https://github.com/Kerndog73/The-Fat-Controller"
readme = "README.md"
categories = ["os::macos-apis", "os::windows-apis", "os::linux-apis"]
license = "MIT"
exclude = [".gitignore", ".idea", "docs", "iOS_client"]

[profile.release]
lto = true
